module.exports = {
  moduleDirectories: ['node_modules', '<rootDir>/'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'esbuild-jest',
  },
  clearMocks: true,
  collectCoverage: false,
  coverageDirectory: 'coverage',
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
  testEnvironment: 'jest-environment-jsdom',
  setupFiles: ['<rootDir>/jest.setup.js'],
  setupFilesAfterEnv: ['@testing-library/jest-dom', '<rootDir>/test/setupTests.js'],
  coverageReporters: ['lcov', 'json', 'clover', 'text'],
  coveragePathIgnorePatterns: ['node_modules', 'demo', 'examples', 'lib', 'scripts', 'types', 'dist', 'coverage'],
  reporters: ['default', ['jest-junit', { outputDirectory: 'coverage', outputName: 'report.xml' }]],
  testMatch: ['<rootDir>/test/**/*.spec.(js|jsx)'],
  moduleNameMapper: {
    '^react$': '<rootDir>/node_modules/react',
    '^react-dom(.*)$': '<rootDir>/node_modules/react-dom$1',
    '^@playerstack/core$': '<rootDir>/../core/src/index.ts',
    '^@playerstack/core/hooks$': '<rootDir>/../core/src/hooks/index.ts',
    '^@playerstack/core/patterns$': '<rootDir>/../core/src/patterns.ts',
    '^@playerstack/core/chapters$': '<rootDir>/../core/src/chapters.ts',
    '^@playerstack/core/heatmap$': '<rootDir>/../core/src/heatmap.ts',
    '^@playerstack/core/i18n$': '<rootDir>/../core/src/i18n/index.ts',
    '^@playerstack/core/keyboard$': '<rootDir>/../core/src/keyboard.ts',
    '^@playerstack/core/live-dvr$': '<rootDir>/../core/src/live-dvr.ts',
    '^@playerstack/core/slider$': '<rootDir>/../core/src/slider.ts',
    '^@playerstack/core/player-state$': '<rootDir>/../core/src/player-state.ts',
    '^@playerstack/core/quality$': '<rootDir>/../core/src/quality.ts',
    '^@playerstack/core/reducer$': '<rootDir>/../core/src/reducer.ts',
    '^@playerstack/core/ui$': '<rootDir>/../core/src/ui.ts',
    '^@playerstack/core/engine$': '<rootDir>/../core/src/media-engine.ts',
    '^@playerstack/core/adapters$': '<rootDir>/../core/src/types/adapters.types.ts',
    '^@playerstack/core/utils/format$': '<rootDir>/../core/src/utils/format.ts',
    '^@playerstack/core/utils/cookie$': '<rootDir>/../core/src/utils/cookie.ts',
    '^@playerstack/core/utils/device$': '<rootDir>/../core/src/utils/device.ts',
    '^@playerstack/core/utils/sdk$': '<rootDir>/../core/src/utils/sdk.ts',
    '^@playerstack/core/utils/media$': '<rootDir>/../core/src/utils/media.ts',
    '^@playerstack/core/utils/env$': '<rootDir>/../core/src/utils/env.ts',
    '^@playerstack/core/utils/captions$': '<rootDir>/../core/src/utils/captions.ts',
    '^@playerstack/core/utils/vtt-sprite$': '<rootDir>/../core/src/utils/vtt-sprite.ts',
    '^@playerstack/core/constants$': '<rootDir>/../core/src/constants.ts',
    '^@playerstack/core/icons/mobile$': '<rootDir>/../core/src/icons/mobile/index.ts',
    '^@playerstack/core/icons$': '<rootDir>/../core/src/icons/index.ts',
  },
};
